### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by cybrnook**
Added some additional words to help clarify Debug options.

### CODE REVIEW

**Comment by jlesage** [comment]
Thanks for your input!  The README cannot be specific to unRAID, since this Docker container is used on multiple systems other than unRAID.

**Comment by jlesage** [comment]
Also, why do you have to chmod the core dump?

**Comment by cybrnook** [comment]
No worries, I had just unRAID in mind when typing it up.

What I noticed is that when the dump is created (/config/* for example), it's written out as either 600 or 700. Perhaps this is because of the default umask settings of the container, not sure? But, what happens is if you want to then copy that dump to your local PC for upload, you will get a permission denied since group and other have no read access. Thus 755 opens up the file, and you can "read" it off.

**Comment by cybrnook** [comment]
I'm sure a chmod +r would also work just as well.

**Comment by jlesage** [comment]
Ok so I guess the user that was accessing the file was not the same as the one running the container?

**Comment by cybrnook** [comment]
Exactly! /config from the container, is my mapped /appdata/handbrake folder. /appdata is an exported share I have from my unRAID server. So when I am upstairs on my windows PC, as my unRAID general ADMIN user, this user does not have access to read the dump as it was produced, since they are two different users. Hence the need to chmod to be able to copy it to my windows desktop, and then upload to you.

**Comment by jlesage** [comment]
Ok thanks, I will try to incorporate your comments without being too specific to unRAID.

**Comment by jlesage** [comment]
I update the README section with commit ae62b67 with your suggestions.
Let me know if it's better or not.

**Pull request closed without merging**
